### ISSUE TITLE
compile json schema to elm?

### ISSUE THREAD

**Issue by donpdonp** [NoRedInk/json-elm-schema#11]
Is it possible to go in the opposite direction? I'd like to have a canonical set of objects described by json schema files, then generate elm records from that. Then I'd know the elm web app is up to date with the fields available on objects that get serialized to the server.

**Comment by jwoudenberg** [comment]
Work has been done to parse ordinary JSON schema files into an Elm JSON Schema type and we also have a Fuzzer for Elm JSON Schema types which generates random JSON strings corresponding to a schema. That could be used to test if some Elm decoder can handle content conforming to a schema. Is that what you're looking for, or am I misunderstanding?

**Comment by donpdonp** [comment]
yes that is what I am looking for, parse ordinary JSON schema files into an Elm type. Is this something I can try now, or is it still being worked on?

**Comment by jwoudenberg** [comment]
You can do it now, with some caveats. The decoder you can use on the JSON schema string is here: http://package.elm-lang.org/packages/NoRedInk/json-elm-schema/1.5.0/JsonSchema-Decoder

- Some part of the spec are not (yet) supported. Give a shout if you're running into issues, I'd be interested to learn what they are.
- There's no CLI tool for this yet and Elm can not read from a file, so if you have a schema.json file somewhere that you'd like to try this with, the best option you currently have is copying it into a multiline string and working from there.

**Comment by jpierson** [comment]
@jwoudenberg, any documentation on where to get started with JsonSchema.Decoder? I looked through it and so far I feel I'm either looking for it to do something it doesn't do or I'm just lost. Basically I'm looking to generate the necessary Elm code/data-structure based on a source JSON Schema so that I can then process json files that conform to that schema in Elm. Please let me know if I'm in the wrong place. Thanks!
